// src/components/ui/copy-button/copy-button.tsx
"use client";

import Image from "next/image";

interface Props {
    userName: React.ReactNode;
    url: string;
    isMailAddress: boolean;
    className?: string;
}

const CopyButton = ({ userName, url, isMailAddress, className="" }: Props) => {
    const handleCopy = () => {
        try {
            let copyText = (url === "#") ? userName?.toString() ?? "" : url;

            if (isMailAddress) {
                copyText = copyText.replace(",[object Object],", "@");
                copyText = copyText.replace(",[object Object],", ".");
            }

            navigator.clipboard.writeText(copyText);
        } catch {
            alert("コピーに失敗しました。やり直してみてください。");
        }

    }

    return (
        <div className={`${className}
                        h-10 w-10 rounded-full
                        transition-all duration-300
                        flex items-center justify-center
                        bg-gray-800
                        drop-shadow-lg active:drop-shadow-none
                        active:bg-gray-500`}
            >
            <button type="button" title="コピー" className="">
                <Image src="/icons/copy.svg" width={20} height={20} alt="コピー" onClick={handleCopy} className="m-2"/>
            </button>
        </div>
    );
}

export default CopyButton;

// src/components/Svelte/ui/CopyButton/CopyButton.svelte
<script lang="ts">
    import clsx from 'clsx';

    interface Props {
        url: string;
        size?:number;
        className?: string;
    }
    const { url, size=25, className }: Props = $props();
</script>

<button class={clsx(className, `flex justify-center items-center
                                transition-all duration-300
                                w-15 h-15 m-2 p-3
                                bg-zinc-800 dark:bg-zinc-100
                                shadow-zinc-500 shadow-md
                                active:bg-zinc-300 dark:active:bg-zinc-600`
)}
        onclick={() => { navigator.clipboard.writeText(url); }}>

    <img src="/icons/light/copy.svg" alt="copy" width={size} class="block dark:hidden" />
    <img src="/icons/dark/copy.svg" alt="copy" width={size} class="hidden dark:block" />
</button>
